# Generated by Django 4.0.4 on 2022-04-20 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=4, unique=True),
        ),
    ]
