# Generated by Django 4.0.4 on 2022-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
